import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img:"https://images-na.ssl-images-amazon.com/images/I/41y2KJ+kDLL._SY344_BO1,204,203,200_.jpg",
    title: "You Can WIN",
    author: "Shiv Khera",
    originalPrice: 1399,
    isBestSeller: true,
    price:5000,
    categoryName: "non-fiction",
    rating: 4.7,
  },
  {
    _id: uuid(),
    img:"https://images-na.ssl-images-amazon.com/images/I/41y2KJ+kDLL._SY344_BO1,204,203,200_.jpg",
    title: "A Touch of Eternity",
    author: "Datta Durjoy",
    originalPrice: 199,
    isBestSeller: true,
    price: 199,
    categoryName: "romance",
    rating: 4,
  },
  {
    _id:uuid(),
    img:"https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
    title: "That Night: Four Friends. ",
    author: "Nidhi Upadhyay ",
    originalPrice: 250,
    isBestSeller: false,
    price: 181,
    categoryName: "horror",
    rating: 4.3,
  },
  {
    _id: uuid(),
    title: "You are Winner",
    img:"https://images-eu.ssl-images-amazon.com/images/I/517sWS8zu0L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    author: "Junaid Qureshi",
    originalPrice: 1399,
    isBestSeller: true,
    price: 3000,
    categoryName: "horror",
    rating: 4.0,
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    img:"https://m.media-amazon.com/images/I/61b5aPmEhzL._AC_UY327_FMwebp_QL65_.jpg",
    author: "Shiv Khera",
    originalPrice: 1399,
    isBestSeller: true,
    price: 1000,
    categoryName: "fiction",
    rating: 3.6,
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwxv98w0/book/l/z/y/do-epic-shit-original-imag9gcfcwfvwtep.jpeg?q=70",
    title: "Do Epic Shit",
    author: "Ankur Warikoo",
    price: 1019,
    originalPrice: 1399,
    isBestSeller: true,
    categoryName: "Self Help",
    rating: 4.6,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/jpu324w0/book/0/9/0/believe-in-yourself-original-imafbzz2h7yfg5zz.jpeg?q=70",
    title: "Believe In Yourself",
    author: "Joseph",
    price: 5,
    originalPrice: 1200,
    isBestSeller: false,
    categoryName: "Self Help",
    rating: 4,
    },

  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kokdci80/regionalbooks/t/x/c/zero-to-one-original-imag2zzngtfasecu.jpeg?q=70",
    title: "Zero To One",
    author: "Peter Thiel",
    price: 50,
    originalPrice: 500,
    isBestSeller: false,
    categoryName: "fiction",
    rating: 2,
    },
  {
    _id: uuid(),
    img: "https://d3i5mgdwi2ze58.cloudfront.net/hwi2qqngyicqz7s7ps4x4k1ei14k",
    title: "Atomic Habits",
    author: "James Clear",
    price: 390,
    originalPrice: 790,
    isBestSeller: true,
    categoryName: "Self Help",
    rating: 4.8,
    },

  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTvrBNWlYmmsa_2M3BaJdurD9lve0SdNLAIA&usqp=CAU",
    title: "IKIGAI",
    author: "I dont Know",
    price: 600,
    originalPrice: 1500,
    isBestSeller: false,
    categoryName: "non-fiction",
    rating: 4,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kgwld3k0/book/1/9/4/rich-dad-poor-dad-original-imafxf885pytvycy.jpeg?q=70",
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyoski",
    price: 350,
    originalPrice: 500,
    isBestSeller: false,
    categoryName: "non-fiction",
    rating: 2,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kirr24w0-0/book/k/k/g/the-monk-who-sold-his-ferrari-original-imafyhgacv9jrgv7.jpeg?q=70",
    title: "Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    price: 119,
    originalPrice: 249,
    isBestSeller: false,
    categoryName: "non-fiction",
    rating: 3,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/ki96c280-0/book/3/p/n/one-indian-girl-original-imafy2zrymfbtygz.jpeg?q=70",
    title: "One Indian Girl",
    author: "Chetan Bhagat",
    price: 157,
    originalPrice: 195,
    isBestSeller: false,
    categoryName: "fiction",
    rating: 3,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kjbr8280-0/book/z/r/9/learning-how-to-fly-original-imafyx6zuhvfhv94.jpeg?q=70",
    title: "Learning How To Fly",
    author: "A.P.J Abdul Kalam",
    price: 163,
    originalPrice: 205,
    isBestSeller: false,
    categoryName: "fiction",
    rating: 2.5,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwpam4w0/book/r/a/r/-original-imag9bv6bzstsjgk.jpeg?q=70",
    title: "400 Days",
    author: "Chetan Bhagat",
    price: 699,
    originalPrice: 999,
    isBestSeller: false,
    categoryName: "Self Help",
    rating: 4,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/khxqt8w0-0/book/x/o/v/attitude-is-everything-change-your-attitude-change-your-life-original-imafxtvesfbk8rje.jpeg?q=70",
    title: "Attitude Is Everything",
    author: "Keller Jeff",
    price: 399,
    originalPrice: 699,
    isBestSeller: false,
    categoryName: "Self Help",
    rating: 3.5,
    },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/p/3/d/man-s-search-for-meaning-original-imag7kerxrpweqj9.jpeg?q=70",
    title: "Man's Search For Meaning",
    author: "Franky Viktor",
    price: 243,
    originalPrice: 349,
    isBestSeller: false,
    categoryName: "non-fiction",
    rating: 1,
   },
];
